version: "3"
services:
    rabbit:
        image:
            rabbitmq:3-management
        ports:
            - "15672:15672"
        environment:
          - RABBITMQ_DEFAULT_USER=stackrabbit
          - RABBITMQ_DEFAULT_PASS=password
        networks:
            cnalan:
                aliases:
                    - rabbit
    redis:
        image:
            redis
        networks:
            cnalan:
                aliases:
                    - redis
    db:
        image: lab7imag/repositorylab7:cloudnativeapp_db
        environment:
            - MYSQL_ROOT_PASSWORD=toto
            - MYSQL_DATABASE=prestashop
            - MYSQL_USER=prestashop
            - MYSQL_PASSWORD=prestashop1234
        networks:
            cnalan:
                aliases:
                    - db
    web:
        image: lab7imag/repositorylab7:cloudnativeapp_web
        ports:
            - "80:80"
        links:
          - i
          - s
          - b
          - p
        networks:
            cnalan:
    i:
        image: lab7imag/repositorylab7:cloudnativeapp_i
        links:
            - db
        networks:
            cnalan:
              aliases:
                - i
    s:
        image: lab7imag/repositorylab7:cloudnativeapp_s
        links:
            - redis
        networks:
            cnalan:
              aliases:
                - s
    b:
        image: lab7imag/repositorylab7:cloudnativeapp_b
        links:
            - w
            - rabbit
        networks:
            cnalan:
              aliases:
                - b
    p:
        image: lab7imag/repositorylab7:cloudnativeapp_p
        networks:
            cnalan:
              aliases:
                - p
    w:
        image: lab7imag/repositorylab7:cloudnativeapp_w
        networks:
            cnalan:
              aliases:
                - w
    w1:
        image: lab7imag/repositorylab7:cloudnativeapp_w1
        links:
          - rabbit
          - redis
        networks:
            cnalan:
              aliases:
                - w1
    w2:
        image: lab7imag/repositorylab7:cloudnativeapp_w2
        links:
          - rabbit
        environment:
          - W2_APIKEY=blakey
          - W2_TO=machin@bidule.com
          - W2_DOMAIN=domain
        networks:
            cnalan:
              aliases:
                - w2
networks:
    cnalan:
        driver: overlay
